name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Allow this workflow to be triggered manually (ex: in GitHub UI)
  workflow_dispatch:

permissions:
  checks: write
  contents: write

jobs:
  lint:
    name: Run Lint
    runs-on: ubuntu-latest
    steps:
      # Checks out the repository and enables the use of commands made available in the project ie npm run
      - name: Checkout Git repository
        uses: actions/checkout@v4

      # Configure npm
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        uses: oven-sh/setup-bun@v2

      - name: enable corepack
        run: "corepack enable"

      - run: "bun install"
        name: Install dependencies

      - name: Build
        run: "bun run build"

      - name: Run linters
        run: "bun run lint"
